
# === BASIC SETTINGS ===
start-at-login = true
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# === MOUSE BEHAVIOR ===
#on-focused-monitor-changed = ['move-mouse monitor-center']
#on-focus-changed = ['move-mouse window-center']

[gaps]
outer.top = 43
outer.bottom = 4
outer.left = 4
outer.right = 4
inner.horizontal = 4
inner.vertical = 4

[mode.main.binding]
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

cmd-enter = 'exec-and-forget /Applications/kitty.app/Contents/MacOS/kitty --single-instance -d ~'

# Uncomment below if you want to toggle between tiling/floating
# alt-space = 'layout floating tiling'

alt-z = 'fullscreen'

# LAYOUT SWITCHING (Optional)
alt-e = 'layout tiles'
alt-s = 'layout floating'

# Switch to workspace 1–9
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

# Move focused window to workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'

# Workspace cycling
alt-tab = 'workspace next'
alt-shift-tab = 'workspace prev'

# === WINDOW RULES ===
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = ['layout floating']

[exec]
inherit-env-vars = true

[exec.env-vars]
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'
